```{r}
library(tidyverse)
```


## Campelen

# Fall

```{r}
load(file = "./ModelSaves/FallCamp_Length.RData")
acc_surv <- read.csv("./Data/Capelin_AccSurv.csv")[1:2] %>% 
  filter(Year > 1994) %>% rename(acsurv_bm = X3L.Spring..Acoustic.Capelin.Biomass..kt.)

# Set up relationship data frame
lr_dat <- data.frame(year = acc_surv[2:28,1], acc_bm = acc_surv[2:28,2], NLFPM_bm = rep$iye) #have to go y+1 

# Linear relationship 
fit <- lm(acc_bm~NLFPM_bm, data = lr_dat)
cor.test(x = lr_dat$NLFPM_bm, y = lr_dat$acc_bm, method = "pearson") # p-values < 0.05: acoustic and NLFPM are significantly correlated 

lr_dat <- na.omit(lr_dat)


fit_cooks <- cooks.distance(fit)
df <- data.frame(obs = names(fit_cooks),
                 cooks = fit_cooks)
ggplot(df, aes(y = cooks, x = obs)) +
  geom_point() +
  geom_hline(yintercept = 0.5, linetype = "dashed") +
  labs(title = "Cook's Distance", x = "Observation Number", y = "Cook's")

lr_dat[which(abs(fit_cooks) > 0.5),]

cor.test(x = c(lr_dat$NLFPM_bm[1:18],lr_dat$NLFPM_bm[20:23]), y = c(lr_dat$acc_bm[1:18],lr_dat$acc_bm[20:23]), method = "pearson")

```

# Spring

```{r}
load(file = "./ModelSaves/AP-SprCamp_Length.RData")
load(file = "./ModelSaves/GH-SprCamp_Length.RData")

acc_surv <- read.csv("./Data/Capelin_AccSurv.csv")[1:2] %>% 
  filter(Year > 1994) %>% rename(acsurv_bm = X3L.Spring..Acoustic.Capelin.Biomass..kt.)

# Set up relationship data frame - ACAP
ap_lr_dat <- data.frame(year = acc_surv[2:25,1], acc_bm = acc_surv[2:25,2], NLFPM_bm = ap_rep$iye)

# This doesnt change corelation coefficient 
ap_lr_dat <- data.frame(year = c(acc_surv[2:18,1], acc_surv[21:25,1]), acc_bm = c(acc_surv[2:18,2], acc_surv[21:25,2]), 
                        NLFPM_bm = c(ap_rep$iye[2:18],ap_rep$iye[21:25]))

# Linear relationship 
fit <- lm(acc_bm~NLFPM_bm, data = ap_lr_dat) # thought is: can NLFPM predict acoustic survey accurately
cor.test(x = ap_lr_dat$NLFPM_bm, y = ap_lr_dat$acc_bm, method = "pearson") # p-values < 0.05: acoustic and NLFPM are significantly correlated 

ap_lr_dat <- na.omit(ap_lr_dat)

fit_cooks <- cooks.distance(fit)
df <- data.frame(obs = names(fit_cooks),
                 cooks = fit_cooks)
ggplot(df, aes(y = cooks, x = obs)) +
  geom_point() +
  geom_hline(yintercept = 0.5, linetype = "dashed") +
  labs(title = "Cook's Distance", x = "Observation Number", y = "Cook's")

ap_lr_dat[which(abs(fit_cooks) > 0.5),] # No influence for AP

cor.test(x = ap_lr_dat$NLFPM_bm, y = ap_lr_dat$acc_bm, method = "pearson")



gh_lr_dat <- data.frame(year = acc_surv[2:25,1], acc_bm = acc_surv[2:25,2], NLFPM_bm = gh_rep$iye)

# This does change the correlation coefficient
gh_lr_dat <- data.frame(year = c(acc_surv[2:18,1], acc_surv[21:25,1]), acc_bm = c(acc_surv[2:18,2], acc_surv[21:25,2]), 
                        NLFPM_bm = c(gh_rep$iye[2:18],gh_rep$iye[21:25]))

# Linear relationship 
fit <- lm(acc_bm~NLFPM_bm, data = gh_lr_dat) # thought is: can NLFPM predict acoustic survey accurately
cor.test(x = gh_lr_dat$NLFPM_bm, y = gh_lr_dat$acc_bm, method = "pearson") # p-values < 0.05: acoustic and NLFPM are significantly correlated 

gh_lr_dat <- na.omit(gh_lr_dat)

fit_cooks <- cooks.distance(fit)
df <- data.frame(obs = names(fit_cooks),
                 cooks = fit_cooks)
ggplot(df, aes(y = cooks, x = obs)) +
  geom_point() +
  geom_hline(yintercept = 0.5, linetype = "dashed") +
  labs(title = "Cook's Distance", x = "Observation Number", y = "Cook's")

gh_lr_dat[which(abs(fit_cooks) > 0.5),] # No influence for GH


```


## Engel

# Fall

```{r}
load(file = "./ModelSaves/ACAP-FallEng_Length.RData")
load(file = "./ModelSaves/GH-FallEng_Length.RData")

acc_surv <- read.csv("./Data/Capelin_AccSurv.csv")[1:2] %>% 
  filter(Year > 1980 & Year < 1996) %>% rename(acsurv_bm = X3L.Spring..Acoustic.Capelin.Biomass..kt.) 

# Set up relationship data frame - ACAP
ac_lr_dat <- data.frame(year = acc_surv[2:15,1], acc_bm = acc_surv[2:15,2], NLFPM_bm = ac_rep$iye) #have to y+1

# Linear relationship 
fit <- lm(acc_bm~NLFPM_bm, data = ac_lr_dat) # thought is: can NLFPM predict acoustic survey accurately
cor.test(x = ac_lr_dat$NLFPM_bm, y = ac_lr_dat$acc_bm, method = "pearson") # p-values < 0.05: acoustic and NLFPM are significantly correlated 

ac_lr_dat <- na.omit(ac_lr_dat)

fit_cooks <- cooks.distance(fit)
df <- data.frame(obs = names(fit_cooks),
                 cooks = fit_cooks)
ggplot(df, aes(y = cooks, x = obs)) +
  geom_point() +
  geom_hline(yintercept = 0.5, linetype = "dashed") +
  labs(title = "Cook's Distance", x = "Observation Number", y = "Cook's")

ac_lr_dat[which(abs(fit_cooks) > 0.5),] # No influence for AC


# Set up relationship data frame - GH
gh_lr_dat <- data.frame(year = acc_surv[2:15,1], acc_bm = acc_surv[2:15,2], NLFPM_bm = gh_rep$iye)

# Linear relationship 
fit <- lm(acc_bm~NLFPM_bm, data = gh_lr_dat) # thought is: can NLFPM predict acoustic survey accurately
cor.test(x = gh_lr_dat$NLFPM_bm, y = gh_lr_dat$acc_bm, method = "pearson") # p-values < 0.05: acoustic and NLFPM are significantly correlated 

gh_lr_dat <- na.omit(gh_lr_dat)

fit_cooks <- cooks.distance(fit)
df <- data.frame(obs = names(fit_cooks),
                 cooks = fit_cooks)
ggplot(df, aes(y = cooks, x = obs)) +
  geom_point() +
  geom_hline(yintercept = 0.5, linetype = "dashed") +
  labs(title = "Cook's Distance", x = "Observation Number", y = "Cook's")

gh_lr_dat[which(abs(fit_cooks) > 0.5),] # No influence for GH

```

# Spring

```{r}
load(file = "./ModelSaves/ACAP-SprEng_Length.RData")
load(file = "./ModelSaves/GH-SprEng_Length.RData")

acc_surv <- read.csv("./Data/Capelin_AccSurv.csv")[1:2] %>% 
  filter(Year > 1983 & Year < 1996) %>% rename(acsurv_bm = X3L.Spring..Acoustic.Capelin.Biomass..kt.)

# Set up relationship data frame - ACAP
ac_lr_dat <- data.frame(year = acc_surv[2:13,1], acc_bm = acc_surv[2:13,2], NLFPM_bm = c(ac_rep$iye[12], ac_rep$iye[1:11])) #have to y+1

# Linear relationship 
fit <- lm(acc_bm~NLFPM_bm, data = ac_lr_dat) # thought is: can NLFPM predict acoustic survey accurately
cor.test(x = ac_lr_dat$NLFPM_bm, y = ac_lr_dat$acc_bm, method = "pearson") # p-values < 0.05: acoustic and NLFPM are significantly correlated 

ac_lr_dat <- na.omit(ac_lr_dat)

fit_cooks <- cooks.distance(fit)
df <- data.frame(obs = names(fit_cooks),
                 cooks = fit_cooks)
ggplot(df, aes(y = cooks, x = obs)) +
  geom_point() +
  geom_hline(yintercept = 0.5, linetype = "dashed") +
  labs(title = "Cook's Distance", x = "Observation Number", y = "Cook's")

ac_lr_dat[which(abs(fit_cooks) > 0.5),] # 1988 influence

cor.test(x = c(ac_lr_dat$NLFPM_bm[1:3],ac_lr_dat$NLFPM_bm[5:8]), y = c(ac_lr_dat$acc_bm[1:3],ac_lr_dat$acc_bm[5:8]), method = "pearson")


# Set up relationship data frame - GH
gh_lr_dat <- data.frame(year = acc_surv[2:13,1], acc_bm = acc_surv[2:13,2], NLFPM_bm = c(gh_rep$iye[12], gh_rep$iye[1:11]))

# Linear relationship 
fit <- lm(acc_bm~NLFPM_bm, data = gh_lr_dat) # thought is: can NLFPM predict acoustic survey accurately
cor.test(x = gh_lr_dat$NLFPM_bm, y = gh_lr_dat$acc_bm, method = "pearson") # p-values < 0.05: acoustic and NLFPM are significantly correlated 

gh_lr_dat <- na.omit(gh_lr_dat)

fit_cooks <- cooks.distance(fit)
df <- data.frame(obs = names(fit_cooks),
                 cooks = fit_cooks)
ggplot(df, aes(y = cooks, x = obs)) +
  geom_point() +
  geom_hline(yintercept = 0.5, linetype = "dashed") +
  labs(title = "Cook's Distance", x = "Observation Number", y = "Cook's")

gh_lr_dat[which(abs(fit_cooks) > 0.5),] # 1988 influence

cor.test(x = c(gh_lr_dat$NLFPM_bm[1:3],gh_lr_dat$NLFPM_bm[5:8]), y = c(gh_lr_dat$acc_bm[1:3],gh_lr_dat$acc_bm[5:8]), method = "pearson")

```

# Spatial

```{r}
load(file = "./ModelSaves/FallCamp_Length.RData")

# Set up relationship data frame
lr_dat <- data.frame(year = unique(fishy_dat$year)[1:26], jkl_NLFPM_bm = rep$iye[1:26])

load(file = "./ModelSaves/3LFallCamp_Length.RData")

lr_dat$l_NLFPM_bm <- rep$iye

# Linear relationship 
fit <- lm(jkl_NLFPM_bm~l_NLFPM_bm, data = lr_dat)
cor.test(x = lr_dat$jkl_NLFPM_bm, y = lr_dat$l_NLFPM_bm, method = "pearson") # p-values < 0.05: acoustic and NLFPM are significantly correlated


fit_cooks <- cooks.distance(fit)
df <- data.frame(obs = names(fit_cooks),
                 cooks = fit_cooks)
ggplot(df, aes(y = cooks, x = obs)) +
  geom_point() +
  geom_hline(yintercept = 0.5, linetype = "dashed") +
  labs(title = "Cook's Distance", x = "Observation Number", y = "Cook's")

lr_dat[which(abs(fit_cooks) > 0.5),] # 1996 influence

cor.test(x = c(gh_lr_dat$NLFPM_bm[1],gh_lr_dat$NLFPM_bm[3:26]), y = c(gh_lr_dat$acc_bm[1],gh_lr_dat$acc_bm[3:26]), method = "pearson")


```










